/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'collections',
    path: '/collections',
    component: 'layout.base$view.collections',
    meta: {
      title: '枚举值管理',
      i18nKey: 'route.collections',
      icon: 'mdi:format-list-bulleted',
      order: 7
    }
  },
  {
    name: 'data-quality',
    path: '/data-quality',
    component: 'layout.base$view.data-quality',
    meta: {
      title: '数据质量',
      i18nKey: 'route.data-quality',
      icon: 'mdi:shield-check',
      order: 9
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'images',
    path: '/images',
    component: 'layout.base$view.images',
    meta: {
      title: '图片资产',
      i18nKey: 'route.images',
      icon: 'mdi:image',
      order: 4
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ocr',
    path: '/ocr',
    component: 'layout.base$view.ocr',
    meta: {
      title: 'OCR 扫描',
      i18nKey: 'route.ocr',
      icon: 'mdi:scan-helper',
      order: 5
    }
  },
  {
    name: 'rates',
    path: '/rates',
    component: 'layout.base$view.rates',
    meta: {
      title: '运费费率',
      i18nKey: 'route.rates',
      icon: 'mdi:cash',
      order: 6
    }
  },
  {
    name: 'records',
    path: '/records',
    component: 'layout.base$view.records',
    meta: {
      title: '运输记录',
      i18nKey: 'route.records',
      icon: 'mdi:file-document',
      order: 2
    }
  },
  {
    name: 'report',
    path: '/report',
    component: 'layout.base$view.report',
    meta: {
      title: '月度报表',
      i18nKey: 'route.report',
      icon: 'mdi:chart-bar',
      order: 8
    }
  },
  {
    name: 'review',
    path: '/review',
    component: 'layout.base$view.review',
    meta: {
      title: '人工核对',
      i18nKey: 'route.review',
      icon: 'mdi:check-circle',
      order: 3
    }
  }
];
